name: CarWashApp CI/CD

on:
  push:
    branches:
      - developer
      - main
  pull_request:
    branches:
      - developer
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: backend
        run: mvn clean install -DskipTests=false

      - name: Run tests
        working-directory: backend
        run: mvn test

      - name: Checkstyle
        working-directory: backend
        run: mvn checkstyle:check || true
